# note, when upgrading lts:
# $ stack build --copy-compiler-tool implicit-hie
# $ stack build --copy-compiler-tool ormolu
# $ stack build --copy-compiler-tool hlint
# download new version of haskell-language-server -- see site for deets

resolver: lts-18.19
packages:
  - server
extra-deps:
  - implicit-hie-0.1.1.0
