name: satisfactory
version: 0.1.0.0
github: "anup-the-magic/satisfactory"
license: BSD3
author: "Anup Kishore"
maintainer: "anup.kishore@gmail.com"
copyright: "MIT"

extra-source-files:
  - README.md
  - ChangeLog.md

description: >
  Please see the README on GitHub at
  <https://github.com/anup-the-magic/haskell-gaming/blob/hanabi/satisfactory/server>


dependencies:
  - base >= 4.7 && < 5
  - containers
  - aeson

_dev:
  dependencies: &dev-dependencies
    ormolu:
    hlint:

_base-exe: &base-exe
  main: Main.hs
  dependencies:
    - satisfactory
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

library:
  source-dirs: src

executables:
  satisfactory-exe:
    <<: *base-exe
    source-dirs: app

tests:
  satisfactory-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      <<: *dev-dependencies
      satisfactory: {}
